### ISSUE TITLE
Convert the CSV read-model to use projectionkit/sqlite.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/example#20]

**Comment by jmalloc** [comment]
Make sure to read the SQLite for Go FAQ, as there's a few gotchas - https://github.com/mattn/go-sqlite3#faq

**Comment by koden-km** [comment]
https://golang.org/pkg/database/sql/

**Comment by koden-km** [comment]
Account projection data:
* id
* customerId
* balance

**Comment by koden-km** [comment]
This old projection will be replaced by #34

**Comment by jmalloc** [comment]
This was removed in #38 :+1:
