### ISSUE TITLE
Rename `domain.makeInstanceID()`.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/example#25]
This function is specifically for the daily debit limit. Perhaps it should be a method on that handler, rather than package-scoped.

**Comment by koden-km** [comment]
All the `transaction.go` `HandleCommand()` helper fuctions should also be added as methods on the handler?

**Comment by jmalloc** [comment]
That would be ok too, but they don't **have** to be. What I had really intended to draw attention to is the fact that `makeInstanceID()` is a very generic name that only applies to a single handler.  It could also be renamed to `makeDailyDebitLimitInstanceID()` but that seems a bit noisy.

**Comment by koden-km** [comment]
Hmm I feel if I move the instance function to be a a method on the handler, then I should do the others in transaction also for consistency.
