### ISSUE TITLE
Add scheduled transactions feature to example.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/example#5]
This is a typical banking feature. "As an account holder I want to transfer money to another account at some predetermined time in the future."

Not suggesting recurring transfers or anything here.

**Comment by koden-km** [comment]
We decided to make this feature recurring for the example now?

Will it be a daily recurring thing? Do show that as a runnable example, we will need to modify "time now".

**Comment by jmalloc** [comment]
Well, it appears I've lied to you. I thought we were always doing recurring transfers, but clearly I disagree with myself 😕 

We should probably decide based on what makes for a better example of timeout features.

**Comment by jmalloc** [comment]
As discussed let's stick with a once-off scheduled transaction (not recurring).  Leave off the "cancel scheduled transaction" feature for a second round of changes if it seems like it would make for a better example.
