### ISSUE TITLE
Have each message implement `dogma.DescribableMessage`.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/example#56]
See https://pkg.go.dev/github.com/dogmatiq/dogma?tab=doc#DescribableMessage.

**Comment by jmalloc** [comment]
Kev, do you think this might be a bit easier now using the guidelines we developed at cwx?

**Comment by koden-km** [comment]
Yeah I think so. Did we document those guidelines anywhere for future reference?

**Comment by jmalloc** [comment]
Only in the comments of PRs, I wonder if we should start maintaining a "best practices" document in `dogmatiq/dogma`.

**Comment by koden-km** [comment]
Some kind of "best practices" document would be pretty great.

**Comment by jmalloc** [comment]
> Some kind of "best practices" document would be pretty great.

Created an issue for this at https://github.com/dogmatiq/dogma/issues/135.
