### ISSUE TITLE
Update all godoc.org URLs to pkg.go.dev. 

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/example#58]
See dogmatiq/dogma#112 and https://github.com/dogmatiq/dogma/commit/b3c44070d40e06ef521bec040e0729d9bc84450b for an example.

**Comment by 0b01001110** [comment]
Hi @jmalloc  ,  can I try this?

**Comment by jmalloc** [comment]
Sure, thank you :)  I think for this project there's only one place to be changed - the link in the top of the README.md file.

**Comment by jmalloc** [comment]
Fixed in #79.
