### ISSUE TITLE
Use Go v1.15 in CI configuration.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/example#67]
See the [template repo CI configuration](https://github.com/dogmatiq/template/blob/96ae9196e3873a437f61a80a5a127ca4879fbc34/.github/workflows/ci.yml#L17).

**Comment by jmalloc** [comment]
We've also been bumping up the minimum Go requirement in go.mod for anything that hasn't reached v1 yet.

**Comment by 0b01001110** [comment]
Hi @jmalloc , can I work on this?

**Comment by jmalloc** [comment]
Sure thing!  

Can I ask how you found this project and why you are interested in contributing? I am assuming it's related to the "good first issue" label.

**Comment by 0b01001110** [comment]
Thank you (^O^)／
I wanted to contribute to OSS, but I had never done so. So I was looking for something that looked easy.
I was also looking for relatively frequent development repository using golang.
