### ISSUE TITLE
Add Validate() methods to each message.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/example#97]
Double check the handlers to ensure that they are not validating things that should be handled in per-message validation.

**Comment by koden-km** [comment]
Each command/event should implement validate:
https://github.com/dogmatiq/dogma/blob/master/message.go#L74

The engine will automatically call these validation methods if they exist.

Example `messages/commands/withdrawal.go` would have:
```go
func (m Withdraw) Validate() error {
	if m.ScheduledDate == "" {
		return errors.New("Withdraw needs a validate scheduled date")
	}

	return nil
}
```

**Comment by jmalloc** [comment]
FWIW, in the case of that date you could actually parse it properly using the same logic that's currently used within the handlers.

**Comment by jmalloc** [comment]
This was fixed in https://github.com/dogmatiq/example/pull/99.
